// Code generated by yapbc. DO NOT EDIT.
// source: test/k11s\test1.proto

package k11s

import (

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessMode int32

const (
    AccessMode_ReadWriteOnce    AccessMode = 0;
    AccessMode_ReadOnlyMany    AccessMode = 1;
    AccessMode_ReadWriteMany    AccessMode = 2;
    AccessMode_ReadWriteOncePod    AccessMode = 3;
)

// Enum value maps for AccessMode
var (
    AccessMode_name = map[int32]string{
        0: "ReadWriteOnce",
        1: "ReadOnlyMany",
        2: "ReadWriteMany",
        3: "ReadWriteOncePod",
    }
    AccessMode_value = map[string]int32{
        "ReadWriteOnce": 0,
        "ReadOnlyMany": 1,
        "ReadWriteMany": 2,
        "ReadWriteOncePod": 3,
    }
)

func (x AccessMode) Enum() *AccessMode {
    p := new(AccessMode)
	*p = x
	return p
}

func (x AccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_test1_enumTypes[0].Descriptor()
}

func (AccessMode) Type() protoreflect.EnumType {
	return &file_test1_enumTypes[0]
}

func (x AccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessMode.Descriptor instead.
func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return file_test1_rawDescGZIP(), []int{0}
}

var file_test1_enumTypes = make([]protoimpl.EnumInfo, 1)

var File_test1 protoreflect.FileDescriptor

const file_test1_rawDesc = "" +
	"\n" +
	"\x15test/k11s\\test1.proto*Z\n" +
	"\n" +
	"AccessMode\x12\x11\n" +
	"\rReadWriteOnce\x10\x00\x12\x10\n" +
	"\x0cReadOnlyMany\x10\x01\x12\x11\n" +
	"\rReadWriteMany\x10\x02\x12\x14\n" +
	"\x10ReadWriteOncePod\x10\x03B\x06Z\x04k11sb\x06proto3"

var (
    file_test1_rawDescOnce sync.Once
    file_test1_rawDescData []byte
)

func file_test1_rawDescGZIP() []byte {
	file_test1_rawDescOnce.Do(func() {
		file_test1_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test1_rawDesc), len(file_test1_rawDesc)))
	})
	return file_test1_rawDescData
}

var file_test1_msgTypes = make([]protoimpl.MessageInfo, 0)
var file_test1_goTypes = []any{
    (AccessMode)(0), // 0: AccessMode
}
var file_test1_depIdxs = []int32{
    0, // [1:1] is the sub-list for method output_type
    0, // [1:1] is the sub-list for method input_type
    0, // [1:1] is the sub-list for extension type_name
    0, // [1:1] is the sub-list for extension extendee
    0, // [0:0] is the sub-list for field type_name
}

func init() { file_test1_init() }
func file_test1_init() {
	if File_test1 != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test1_rawDesc), len(file_test1_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test1_goTypes,
		DependencyIndexes: file_test1_depIdxs,
		MessageInfos:      file_test1_msgTypes,
        EnumInfos:         file_test1_enumTypes,
	}.Build()
	File_test1 = out.File
	file_test1_goTypes = nil
	file_test1_depIdxs = nil
}
        