# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: test.proto
# This file has been @generated

from dataclasses import dataclass

import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)

__all__ = (
    "VolumeMount",
)


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class VolumeMount(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    mount_path: str = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=False, optional=False)

    def __init__(
            self,
            *,
            name: str,
            mount_path: str,

    ):
        """
        :param name: - 
        :param mount_path: - 
        """
        self.name = name
        self.mount_path = mount_path

        self._unknown_fields = b""


default_message_pool.register_message("", "VolumeMount", VolumeMount)
