# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: test.proto, test1.proto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class VolumeClaimTemplate(betterproto2.Message):
    """
    pvc
    """

    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    access_modes: List["AccessMode"] = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    storage_class_name: str = betterproto2.field(3, betterproto2.TYPE_STRING, repeated=False, optional=False)
    storage: str = betterproto2.field(4, betterproto2.TYPE_STRING, repeated=False, optional=False)

    def __init__(
            self,
            *,
            name: str,
            access_modes: List["AccessMode"],
            storage_class_name: str,
            storage: str,
    ):
        """
        :param name: - 
        :param access_modes: - 
        :param storage_class_name: - 
        :param storage: - 
        """
        self.name = name
        self.access_modes = access_modes
        self.storage_class_name = storage_class_name
        self.storage = storage

        self._unknown_fields = b""


default_message_pool.register_message("", "VolumeClaimTemplate", VolumeClaimTemplate)


class AccessMode(betterproto2.Enum):
    """
    not pvc
    """

    ReadWriteOnce = 0
    """
    read write once
    """

    ReadOnlyMany = 1
    ReadWriteMany = 2
    ReadWriteOncePod = 3


__all__ = (
    "VolumeClaimTemplate"
)
