# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: test1.proto, test.proto
# This file has been @generated

from typing import List, Optional
from dataclasses import dataclass
import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)

class AccessMode(betterproto2.Enum):
    """
    not pvc
    """

    ReadWriteOnce = 0
    """
    read write once
    """

    ReadOnlyMany = 1
    ReadWriteMany = 2
    ReadWriteOncePod = 3


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class VolumeClaimTemplate(betterproto2.Message):
    """
    pvc
    """

    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    access_modes: List["AccessMode"] = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    storage_class_name: str = betterproto2.field(3, betterproto2.TYPE_STRING, repeated=False, optional=False)
    storage: str = betterproto2.field(4, betterproto2.TYPE_STRING, repeated=False, optional=False)

    def __init__(
        self,
        *,
        name: str, 
        access_modes: List["AccessMode"], 
        storage_class_name: str, 
        storage: str, 
    ):
        """
        :param name: - 
        :param access_modes: - 
        :param storage_class_name: - 
        :param storage: - 
        """
        self.name = name
        self.access_modes = access_modes
        self.storage_class_name = storage_class_name
        self.storage = storage

        self._unknown_fields = b""
        
default_message_pool.register_message("", "VolumeClaimTemplate", VolumeClaimTemplate)

@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class K8SStack(betterproto2.Message):
    namespace: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)

    def __init__(
        self,
        *,
        namespace: str, 
    ):
        """
        :param namespace: - 
        """
        self.namespace = namespace

        self._unknown_fields = b""
        
default_message_pool.register_message("", "K8SStack", K8SStack)

@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class StackTypes(betterproto2.Message):
    k8sstack: "K8SStack | None"= betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True, group="type")
    thing: "VolumeClaimTemplate | None"= betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True, group="type")
    
    def __init__(
        self,
        *,
        
        k8sstack: "K8SStack | None" = None,
        thing: "VolumeClaimTemplate | None" = None, 
    ):
        """
        """
        self.k8sstack = k8sstack
        self.thing = thing

        self._unknown_fields = b""
        
default_message_pool.register_message("", "StackTypes", StackTypes)

@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class Stack(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    stack: "StackTypes" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=False, optional=False)

    def __init__(
        self,
        *,
        name: str, 
        stack: "StackTypes", 
    ):
        """
        :param name: - 
        :param stack: - 
        """
        self.name = name
        self.stack = stack

        self._unknown_fields = b""
        
default_message_pool.register_message("", "Stack", Stack)

__all__ = (
    "VolumeClaimTemplate"

    "K8SStack"

    "StackTypes"

    "Stack"
)
    