// Code generated by yapbc. DO NOT EDIT.
// source: test/test.proto

package k8s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)
type VolumeMount struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
    
}
            