// Code generated by yapbc. DO NOT EDIT.
// source: test/test.proto

package k8s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeMount struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
    Name  string
    MountPath  string

}
        
func (x *VolumeMount) Reset() {
    *x = VolumeMount{}
	mi := &file_test_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_test_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_test_rawDescGZIP(), []int{1}
}


func (x *VolumeMount) GetName() string {
    if x != nil {
        return x.Name
    }
    return ""
}
        
func (x *VolumeMount) GetMountPath() string {
    if x != nil {
        return x.MountPath
    }
    return ""
}
        

var File_test protoreflect.FileDescriptor

const file_k8s_pod_proto_rawDesc = "" +
    "\n\x0ftest/test.proto\"A\n\x0bVolumeMount\x12\x12\n\x04name" +
    "\x18\x01 \x01(\tR\x04name\x12\x1e\n\nmount_path\x18\x02 \x01(\tR\nmount_" +
    "pathB\x05Z\x03k8sb\x06proto3"

var (
    file_test_rawDescOnce sync.Once
    file_test_rawDescData []byte
)

func file_test_rawDescGZIP() []byte {
	file_test_rawDescOnce.Do(func() {
		file_test_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_rawDesc), len(file_test_rawDesc)))
	})
	return file_test_rawDescData
}

var file_test_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_goTypes = []any{
    (*VolumeMount)(nil), // 0: VolumeMount
}
var file_test_depIdxs = []int32{
	0, // 0: Pod.containers:type_name -> Container
	1, // 1: Pod.mounts:type_name -> VolumeMount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_init() }
func file_test_init() {
	if File_test != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_rawDesc), len(file_test_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_goTypes,
		DependencyIndexes: file_test_depIdxs,
		MessageInfos:      file_test_msgTypes,
	}.Build()
	File_test = out.File
	file_test_goTypes = nil
	file_test_depIdxs = nil
}
        