use std::fs;
use std::path::PathBuf;
use std::process::exit;
use crate::ast::message::Messages;

fn to_snake_case(input: &str) -> String {
    let mut snake = String::new();

    for (i, ch) in input.char_indices() {
        if ch.is_uppercase() {
            if i > 0 {
                snake.push('_');
            }
            snake.extend(ch.to_lowercase());
        } else {
            snake.push(ch);
        }
    }

    snake
}
impl Messages {

    pub fn compile_go(&self, files: Vec<PathBuf>, output: PathBuf) {
        if self.package.is_empty() {
            println!("no package provided");
            exit(1);
        }
        println!("package: {}", self.package);
        for (i, message) in self.messages.iter().enumerate() {
            let name = message.name.clone();
            let source_file = files[i].display();
            let package = self.package.clone();
            let code = format!("\
// Code generated by yapbc. DO NOT EDIT.
// source: {source_file}

package {package}

import (
	protoreflect \"google.golang.org/protobuf/reflect/protoreflect\"
	protoimpl \"google.golang.org/protobuf/runtime/protoimpl\"
	reflect \"reflect\"
	sync \"sync\"
	unsafe \"unsafe\"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type {name} struct {{
    state         protoimpl.MessageState `protogen:\"open.v1\"`

    unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}}
            ", );

            let mut filename = output.clone();
            filename.push(format!("{}.pb.go", to_snake_case(&*message.name)));
            fs::write(&filename, &code).unwrap();
        }
    }
}