use crate::ast::comments::Comments;
use crate::ast::field::Field;
use pest::iterators::Pair;
use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "proto.pest"]
pub struct ProtoParser;


#[derive(Debug, Clone)]
pub struct Message {
    pub name: String,
    pub fields: Vec<Field>,
    pub comments: Comments,
}

impl Message {
    pub fn parse(record: Pair<Rule>) -> Message {
        let mut name = String::new();
        let mut fields = Vec::new();
        let mut comments = Vec::new();
        for record in record.into_inner() {
            match record.as_rule() {
                Rule::ident => name = record.as_str().to_string(),
                Rule::line_comment => {
                    if let Some((_prefix, remainder)) = record.as_str().split_once(' ') {
                        comments.push(remainder.parse().unwrap());
                    } else {
                        comments.push(record.as_str().parse().unwrap());
                    }
                }
                Rule::field => {
                    fields.push(Field::parse(record));
                }
                _ => ()
            }
        }

        Message { name, fields, comments: Comments { comments } }
    }

    pub fn python_compile(&self) -> String {
        let mut code = String::new();
        let mut variables_init = String::new();
        let mut variables_comment = String::new();
        let mut variables_with_default_init = String::new();
        let mut variables_with_default_comment = String::new();
        let mut assignment = String::new();
        for f in &self.fields {
            let (preinit, init, comment) = f.python_compile();
            if f.default.is_some() {
                variables_with_default_init.push_str(format!("        {} = {}, \n", init, f.default.clone().unwrap().as_str()).as_str());
                variables_with_default_comment.push_str(format!("        :param {}: {} \n", f.name.clone(), comment).as_str());
            } else {
                variables_init.push_str(format!("        {}, \n", init).as_str());
                variables_comment.push_str(format!("        :param {}: {} \n", f.name.clone(), comment).as_str());
            }
            code.push_str(format!("    {}", preinit).as_str());
            assignment.push_str(format!("        self.{} = {}\n", f.name, f.name).as_str());
        }

        format!(
            "@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class {}(betterproto2.Message):
{}{}
    def __init__(
        self,
        *,
{}
{}
    ):
        \"\"\"\n{variables_comment}{variables_with_default_comment}        \"\"\"
{assignment}
        self._unknown_fields = b\"\"
        ",
            self.name,
            self.comments.python_compile(),
            code,
            variables_init,
            variables_with_default_init)
    }
}

#[derive(Debug, Clone)]
pub struct Messages {
    pub messages: Vec<Message>,
}

impl Messages {
    pub fn parse(data: String) -> Messages {
        let successful_parse = ProtoParser::parse(Rule::messages, &data)
            .expect("unsuccessful parse")
            .next().unwrap();

        let inner = successful_parse.into_inner();

        if inner.is_empty() {
            panic!("no messages found")
        }

        let mut messages = Vec::new();

        for record in inner {
            match record.as_rule() {
                Rule::message => {
                    messages.push(Message::parse(record));
                }
                _ => {
                    panic!("{}", format!("unrecognised rule: {:?}", record.as_rule()))
                }
            }
        }

        Messages { messages }
    }

    pub fn python_compile(&self) -> String {
        let mut code = String::new();
        code.push_str("\
# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: TO BE ADDED
# This file has been @generated

from typing import List, Optional
from dataclasses import dataclass
import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = \"0.9.0\"
betterproto2.check_compiler_version(_COMPILER_VERSION)

__all__ = (
");

        for message in &self.messages {
            code.push_str(format!("    \"{}\",\n", message.name).as_str());
        }

        code.push_str(")\n\n");

        for message in self.messages.iter() {
            code.push_str(format!("{}\n", message.python_compile()).as_str());
            code.push_str(format!("default_message_pool.register_message(\"\", \"{}\", {})\n\n", message.name, message.name).as_str());
        }

        code
    }
}