// Code generated by yapbc. DO NOT EDIT.
// source: test/k8s\module\test.proto

package module

import (
    k11s "github.com/SuperTapood/Flint/test/k11s"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeClaimTemplate struct {
    state         protoimpl.MessageState
    unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
    Name  string
    AccessModes  []*k11s.AccessMode
    StorageClassName  string
    Storage  string

}
        
func (x *VolumeClaimTemplate) Reset() {
    *x = VolumeClaimTemplate{}
	mi := &file_test_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeClaimTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeClaimTemplate) ProtoMessage() {}

func (x *VolumeClaimTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_test_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeClaimTemplate.ProtoReflect.Descriptor instead.
func (*VolumeClaimTemplate) Descriptor() ([]byte, []int) {
	return file_test_rawDescGZIP(), []int{0}
}


func (x *VolumeClaimTemplate) GetName() string {
    if x != nil {
        return x.Name
    }
    return ""
}
        
func (x *VolumeClaimTemplate) GetAccessModes() []*k11s.AccessMode {
    if x != nil {
        return x.AccessModes
    }
    return nil
}
        
func (x *VolumeClaimTemplate) GetStorageClassName() string {
    if x != nil {
        return x.StorageClassName
    }
    return ""
}
        
func (x *VolumeClaimTemplate) GetStorage() string {
    if x != nil {
        return x.Storage
    }
    return ""
}
        

var File_test protoreflect.FileDescriptor

const file_test_rawDesc = "" +
	"\n" +
	"\x1atest/k8s\\module\\test.proto\"\xa9\x01\n" +
	"\x13VolumeClaimTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x0caccess_modes\x18\x02 \x03(\v2\x10.k11s.AccessModeR\x0caccess_modes\x12.\n" +
	"\x12storage_class_name\x18\x03 \x01(\tR\x12storage_class_name\x12\x18\n" +
	"\x07storage\x18\x04 \x01(\tR\x07storageB\x08Z\x06moduleb\x06proto3"

var (
    file_test_rawDescOnce sync.Once
    file_test_rawDescData []byte
)

func file_test_rawDescGZIP() []byte {
	file_test_rawDescOnce.Do(func() {
		file_test_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_rawDesc), len(file_test_rawDesc)))
	})
	return file_test_rawDescData
}

var file_test_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_goTypes = []any{
    (*VolumeClaimTemplate)(nil), // 0: VolumeClaimTemplate
}
var file_test_depIdxs = []int32{
    0, // [1:1] is the sub-list for method output_type
    0, // [1:1] is the sub-list for method input_type
    0, // [1:1] is the sub-list for extension type_name
    0, // [1:1] is the sub-list for extension extendee
    0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_init() }
func file_test_init() {
	if File_test != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_rawDesc), len(file_test_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_goTypes,
		DependencyIndexes: file_test_depIdxs,
		MessageInfos:      file_test_msgTypes,
        EnumInfos:         nil,
	}.Build()
	File_test = out.File
	file_test_goTypes = nil
	file_test_depIdxs = nil
}
        