mod ast;
mod util;

use crate::ast::message::Messages;
use clap::{Parser, Subcommand};
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::process::exit;
use std::time::Instant;

#[derive(Parser)]
#[command(name = "yapbc")]
#[command(about = "Yet Another Protocol Buffer Compiler", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(clap::ValueEnum, Clone, Debug)]
enum Language {
    Python,
    Go,
}

#[derive(Subcommand)]
enum Commands {
    /// Compile protobuf to a specific language
    Compile {
        #[arg(short, long)]
        /// The protobuf files you want to compile
        files: Vec<PathBuf>,
        #[arg(short, long)]
        /// The output directory for the compiled code.
        output: PathBuf,
        #[arg(short, long, value_enum)]
        /// The Language you want to compile to
        languages: Vec<Language>,
        #[arg(short, long)]
        module: Option<String>,
    },
}

fn compile_python(files: BTreeMap<PathBuf, String>, mut output: PathBuf) {
    let files_str = files
        .iter()
        .map(|(f, _)| f.file_name().unwrap().to_str().unwrap())
        .collect::<Vec<&str>>()
        .join(", ");
    let mut modules = String::new();
    let mut code = String::new();
    code.push_str(
        format!(
            "\
# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: {files_str}
# This file has been @generated

from typing import List, Optional
from dataclasses import dataclass
import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = \"0.9.0\"
betterproto2.check_compiler_version(_COMPILER_VERSION)

"
        )
            .as_str(),
    );
    for (filename, file) in &files {
        let messages = Messages::parse(file.to_string(), filename.to_str().unwrap().to_string());
        code.push_str(&messages.compile_python());
        for message in messages.messages {
            modules.push_str(format!("\n    \"{}\"\n", message.name).as_str());
        }
    }

    code.push_str(format!("\
__all__ = ({modules})
    ").as_str());

    output.push("__init__.py");

    fs::write(&output, &code).unwrap();
}

fn compile(mut files: Vec<PathBuf>, output: PathBuf, language: Language, module: Option<String>) {
    if files.is_empty() {
        println!("No files specified! Specify some using -f/--files");
        exit(1);
    }

    println!("files {:?}", files);

    match language {
        Language::Python => {
            let mut files_contents = BTreeMap::new();

            while let Some(current_path) = files.pop() {
                if !current_path.exists() {
                    println!("File does not exist: {}", current_path.display());
                    exit(1);
                }

                let metadata = fs::metadata(&current_path).expect("Failed to get metadata");

                if metadata.is_dir() {
                    for entry in fs::read_dir(&current_path).expect("Failed to read dir") {
                        let path = entry.expect("Failed to read entry").path();
                        files.push(path);
                    }
                } else {
                    if current_path.extension().unwrap() == "proto" {
                        files_contents.insert(current_path.clone(), fs::read_to_string(&current_path).expect("Failed to read contents"));
                    }
                }
            }
            compile_python(files_contents, output);
        }
        Language::Go => {
            while let Some(current_path) = files.pop() {
                let mut actual_files = Vec::new();
                actual_files.push(current_path.clone());
                while let Some(filename) = actual_files.pop() {
                    let mut files_contents = BTreeMap::new();
                    if !filename.clone().exists() {
                        println!("File does not exist: {}", filename.clone().display());
                        exit(1);
                    }

                    let metadata = fs::metadata(filename.clone()).expect("Failed to get metadata");

                    if metadata.is_dir() {
                        for entry in fs::read_dir(filename.clone()).expect("Failed to read dir") {
                            let path = entry.expect("Failed to read entry").path();
                            actual_files.push(path);
                        }
                    } else {
                        if filename.clone().extension().unwrap() == "proto" {
                            files_contents.insert(filename.clone(), fs::read_to_string(filename.clone()).expect("Failed to read contents"));
                        }
                    }
                    for (file, content) in &files_contents {
                        let mut messages = Messages::parse(content.clone(), file.to_str().unwrap().to_string());
                        messages.compile_go(file.clone(), current_path.clone(), output.clone(), module.clone());
                    }
                }
            }
        }
    }
}

fn main() {
    let start = Instant::now();
    let cli = Cli::parse();

    match &cli.command {
        Commands::Compile {
            files,
            output,
            languages,
            module,
        } => {
            for lang in languages {
                compile(files.clone(), output.clone(), lang.clone(), module.clone())
            }
        }
    }
    let duration = start.elapsed();
    println!("done in {:?}", duration);
}