# Generated by Yet Another Protocol Buffer Compiler. DO NOT EDIT!
# sources: test.proto
# This file has been @generated

from dataclasses import dataclass
from typing import List, Optional

import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)

__all__ = (
    "Container",
    "VolumeMount",
    "Pod",
)


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class Container(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    """
    name
    """

    image: str = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=False, optional=False)
    """
    image
    """

    ports: Optional[List[int]] = betterproto2.field(3, betterproto2.TYPE_INT32, repeated=True, optional=True)
    """
    ports
    and even more ports
    """

    def __init__(
            self,
            *,
            name: str,
            image: str,

            ports: Optional[List[int]] = None,

    ):
        """
        :param name: name  
        :param image: image  
        :param ports: ports and even more ports  
        """
        self.name = name
        self.image = image
        self.ports = ports

        self._unknown_fields = b""


default_message_pool.register_message("", "Container", Container)


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class VolumeMount(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    mount_path: str = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=False, optional=False)

    def __init__(
            self,
            *,
            name: str,
            mount_path: str,

    ):
        """
        :param name: - 
        :param mount_path: - 
        """
        self.name = name
        self.mount_path = mount_path

        self._unknown_fields = b""


default_message_pool.register_message("", "VolumeMount", VolumeMount)


@dataclass(
    kw_only=True,
    init=False,
    eq=False,
    repr=False,
)
class Pod(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    containers: List[Container] = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    mounts: List[VolumeMount] = betterproto2.field(3, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    restart_policy: Optional[str] = betterproto2.field(4, betterproto2.TYPE_STRING, repeated=False, optional=True)

    def __init__(
            self,
            *,
            name: str,
            containers: List[Container],
            mounts: List[VolumeMount],

            restart_policy: Optional[str] = "Always",

    ):
        """
        :param name: - 
        :param containers: - 
        :param mounts: - 
        :param restart_policy: - 
        """
        self.name = name
        self.containers = containers
        self.mounts = mounts
        self.restart_policy = restart_policy

        self._unknown_fields = b""


default_message_pool.register_message("", "Pod", Pod)
