# Generated by Yet Another Protocol Buffer Format compiler. DO NOT EDIT!
# sources: TO BE ADDED
# This file has been @generated

from typing import List
from dataclasses import dataclass
import betterproto2

default_message_pool = betterproto2.MessagePool()

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)

__all__ = (
    "Container",
    "VolumeMount",
    "Pod",
)

@dataclass(
    kw_only=True,
    frozen=True,
    eq=False,
    repr=False,
)
class Container(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    image: str = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=False, optional=False)
    ports: List[int] = betterproto2.field(3, betterproto2.TYPE_INT32, repeated=True, optional=True)

default_message_pool.register_message("", "Container", Container)

@dataclass(
    kw_only=True,
    frozen=True,
    eq=False,
    repr=False,
)
class VolumeMount(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    mount_path: str = betterproto2.field(2, betterproto2.TYPE_STRING, repeated=False, optional=False)

default_message_pool.register_message("", "VolumeMount", VolumeMount)

@dataclass(
    kw_only=True,
    frozen=True,
    eq=False,
    repr=False,
)
class Pod(betterproto2.Message):
    name: str = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=False, optional=False)
    containers: List[Container] = betterproto2.field(2, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    mounts: List[VolumeMount] = betterproto2.field(3, betterproto2.TYPE_MESSAGE, repeated=True, optional=False)
    restart_policy: str = betterproto2.field(4, betterproto2.TYPE_STRING, repeated=False, optional=False)

default_message_pool.register_message("", "Pod", Pod)

